[package]
name = "protofun"
version = "0.1.0"
edition = "2024"

[dependencies]
protobuf = "4.33.2-release"
protobuf-well-known-types = "4.33.2-release"

[build-dependencies]
protobuf-codegen = "4.33.2-release"
protobuf-well-known-types = "4.33.2-release"
